import { notFound } from 'next/navigation';
import Link from 'next/link';
import SiteHeader from '@/components/site-header';
import SiteFooter from '@/components/site-footer';
import ArticleCard from '@/components/article-card';
import { getPublicAuthorBySlug, getPublicAuthors, normalizeCmsArticle } from '@/lib/cms-articles';
import { buildAuthorBreadcrumbJsonLd, buildPageMetadata, serializeJsonLd } from '@/lib/seo';
import { SITE_URL } from '@/lib/site';

export async function generateStaticParams() { return (await getPublicAuthors()).map((author) => ({ slug: author.slug })); }
export async function generateMetadata({ params }) { const { slug } = await params; const data = await getPublicAuthorBySlug(slug); if (!data?.author) return { robots: { index: false, follow: false } }; const author = data.author; return buildPageMetadata({ title: author.name, description: author.role ? `${author.role}. ${author.bio}` : author.bio, pathname: `/authors/${author.slug}`, siteUrl: SITE_URL }); }
export default async function AuthorPage({ params }) { const { slug } = await params; const data = await getPublicAuthorBySlug(slug); if (!data?.author) notFound(); const { author } = data; const articles = (data.articles || []).map(normalizeCmsArticle); const type = author.schema_type === 'organization' ? 'Organization' : 'Person'; const graph = { '@context':'https://schema.org','@type':type,'@id':`${SITE_URL}/authors/${author.slug}#${type.toLowerCase()}`,name:author.name,url:`${SITE_URL}/authors/${author.slug}`,description:author.bio,image:author.image?.url,jobTitle:author.role || undefined,sameAs:author.same_as?.length ? author.same_as : undefined }; const breadcrumbs = buildAuthorBreadcrumbJsonLd(author, SITE_URL);
  return <div className="min-h-screen bg-background"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(graph) }} />{breadcrumbs && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: serializeJsonLd(breadcrumbs) }} />}<SiteHeader /><main className="mx-auto max-w-5xl px-6 pb-24 pt-48 md:pt-56"><Link href="/people" className="font-mono text-[10px] uppercase tracking-[0.2em] text-rose">People</Link><section className="mt-8 border-b border-border/30 pb-12"><div className="flex gap-6">{author.image?.url && <img src={author.image.url} alt={author.image.alt || author.name} className="h-28 w-28 rounded-full object-cover" />}<div><h1 className="font-display text-4xl text-foreground md:text-5xl">{author.name}</h1>{author.role && <p className="mt-3 font-mono text-[10px] uppercase tracking-[0.15em] text-rose">{author.role}</p>}<p className="mt-5 max-w-2xl font-body text-lg leading-relaxed text-muted-foreground">{author.bio}</p>{author.same_as?.length > 0 && <div className="mt-5 flex gap-4">{author.same_as.map((url) => <a key={url} href={url} target="_blank" rel="noreferrer" className="font-mono text-[10px] uppercase tracking-[0.15em] text-rose">Profile</a>)}</div>}</div></div></section><section className="pt-12"><h2 className="mb-8 font-mono text-[10px] uppercase tracking-[0.2em] text-rose">Stories</h2><div className="grid gap-8 md:grid-cols-3">{articles.map((article) => <ArticleCard key={article.slug} article={article} />)}</div></section></main><SiteFooter /></div>;
}
